### ISSUE TITLE
Windows Defender (falsly?) detects it as virus...

### ISSUE THREAD

**Issue by pagebox** [programmer2514/DPEdit#2]
Windows Defender identifies DPEdit.exe 1.3.1 as Trojan (Win32/Wacatac.T!ml). I think it's a false positive, since VirusTotal doesn't identifies it as virus... I guess a re-compile with sligly different code might do the trick...

**Comment by programmer2514** [comment]
Thanks for the report. I'll see what I can do to fix it

**Comment by pagebox** [comment]
Another day, another virus definition update. As of today Windows Defender no longer identifies DPEdit.exe as virus. I've tested at home as well as on my work laptop. both used to alert me, but they don't do anymore. So I think the issue is solved with the update of the pattern file of Defender

**Comment by programmer2514** [comment]
Awesome. I had submitted a false positive report to Microsoft after your initial report, so that may have had something to do with it. Whatever the reason, I'm glad it seems to have been resolved :)
